### ISSUE TITLE
Creating multiple applications via BIG-IQ using the TF bigip_bigiq_as3 resource causes Terraform to error out with "Error: json: cannot unmarshal array into Go value of type map[string]interface {}" after successfully deploying the applications.

### ISSUE THREAD

**Issue by dan-da-man-86** [F5Networks/terraform-provider-bigip#437]
### Environment

 * TMOS/Bigip Version: 15.1.2
 * BIG-IQ Version: 7.1.0.2
 * Terraform Version: 14.7
 * Terraform bigip provider Version: 1.7

### Summary

Creating multiple applications via BIG-IQ (one to each of the 12 BIG-IPs) using the TF bigip_bigiq_as3 resource causes Terraform to error out with "Error: json: cannot unmarshal array into Go value of type map[string]interface {}" after successfully deploying the applications. Subsequent terraform runs fail with this error until the terraform.state is restored to what it was before attempting to deploy the applications. Opened a support ticket (C3499732), but was also advised to open the issue here.

### Steps To Reproduce

Resource config:
resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
  for_each          = local.f5_vm_names
  bigiq_address     = var.bigIqHost
  bigiq_user        = var.bigIqUsername
  bigiq_password    = var.bigIqPassword
  as3_json          = data.template_file.bigip_as3_template[each.key].rendered 
} 

AS3
During troubleshooting, I reverted to the example AS3 found at https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_bigiq_as3 and replaced the target address and application with variables of each BIG-IP.

AS3:
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.7.0",
        "id": "example-declaration-01",
        "label": "Task1",
        "remark": "Task 1 - HTTP Application Service",
        "target": {
            "address": "${local_mgmtip}"
        },
        "Task1": {
            "class": "Tenant",
            "${local_host}": {
                "class": "Application",
                "template": "http",

                "serviceMain": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "10.1.2.10"
                    ],
                    "pool": "web_pool"
                },
                "web_pool": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 80,
                            "serverAddresses": [
                                "192.0.2.33",
                                "192.0.2.13"
                            ],
                            "shareNodes": true
                        }
                    ]
                }
            }
        }
    }
}

### Expected Behavior
Multiple applications deploy successfully through BIG-IQ to all of the BIG-IPs and Terraform completes without error.

### Actual Behavior
Multiple applications deploy successfully through BIG-IQ to all of the BIG-IPs and Terraform errors out before completion and is only able to run again after restoring the state file after each run. 

TF Output
Error: json: cannot unmarshal array into Go value of type map[string]interface {}

  on bigip_as3.tf line 74, in resource "bigip_bigiq_as3" "deploy_as3_to_bigips":
  74: resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {

TF Debug Output
See attached TF debug logs, but it seems to follow the pattern of:
[DEBUG] plugin.terraform-provider-bigip_v1.7.0.exe: 2021/03/01 18:06:10 [INFO] Initializing BigIP connection
[DEBUG] plugin.terraform-provider-bigip_v1.7.0.exe: 2021/03/01 18:06:11 [INFO] Reading As3 config
[DEBUG] plugin.terraform-provider-bigip_v1.7.0.exe: 2021/03/01 18:06:11 [ERROR] Unable to retrieve json

Troubleshooting steps taken:
-Attempted without for_each loop - successfully deployed 1 application
-Attempted without variables - successfully deployed 1 application
-Attempted with for_each loop and variables, where each of the 12 mgmt big-ips were used with the application name - successfully deployed 1 application - the rest failed with duplicate application name
-Attempted BIG-IP provider 1.3.2, 1.6, and 1.7
-Attempted on v13 and v14 of TF - currently testing on 14.7
-Attempted AS3 versions 3.0.0, 3.7.0, and 3.25.0
-Additional information and screenshots in C3499732

[TF BIGIP Provider Debug.txt](https://github.com/F5Networks/terraform-provider-bigip/files/6111146/TF.BIGIP.Provider.Debug.txt)

**Comment by nmenant** [comment]
Created INFRAANO-251 to track this internally.

**Comment by RavinderReddyF5** [comment]
@dan-da-man-86 Issue fixed in v1.8.0, can you please verify with v1.8.0 and let me know if any issues seen

**Comment by dan-da-man-86** [comment]
@RavinderReddyF5, thanks for applying a fix, but unfortunately, while there is an improvement, it still presented with the same error message initially. There is a difference in behavior though. Instead of throwing the error 2 times, it now only throws it one time and it doesn't cause a permanent failure of the state file, where it did before v1.8.0. It does however seem to struggle to keep track of which AS3 was actually applied at which index of the for_each loop, so it's finding changes in the AS3's and having to reapply them when nothing has changed in the AS3. See 3 runs of Terraform apply below for the specific details and thoughts. Basically, it seems to think that it deployed the AS3 for our BIG-IP called azf5orduksoint2 on all 3 BIG-IPs on subsequent runs of Terraform apply, and attempts to re-apply the correct AS3 for each BIG-IP, even though in actuality it had deployed to the correct BIG-IP for each AS3. Unsure if it's just misreading the state file on subsequent runs. Validated in BIG-IQ and each BIG-IP that the AS3 had correctly applied.

===================================
**Terraform apply (initial deployment of the AS3)**
===================================
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Creating...
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Creating...
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Creating...
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Still creating... [10s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [10s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [10s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [20s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Still creating... [20s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [20s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Still creating... [30s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [30s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [30s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [40s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [40s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [50s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [50s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m0s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [1m0s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m10s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Still creating... [1m10s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Creation complete after 1m15s [id=tenantList]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m20s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m30s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m40s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Still creating... [1m50s elapsed]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Creation complete after 1m53s [id=tenantList]

**Error: json: cannot unmarshal object into Go value of type []map[string]interface {}**

  on bigip_as3.tf line 66, in resource "bigip_bigiq_as3" "deploy_as3_to_bigips":
  66: resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {


PS C:\Users\....

================================================
**Terraform apply (ran a 2nd time to see if the state file was erroring out again - did not error out which is a great improvement, but doesn't appear to be properly tracking which AS3 was deployed. For example: bigip_bigiq_as3.deploy_as3_to_bigips["0"]  (first pass of the loop) originally deployed as the 2nd BIG-IP's AS3 (As reported by the state) instead of the 1st one. It may just be reading the state file incorrectly as the applications are correctly deployed to each of the BIG-IPs. The subsequent runs of Terraform apply all try to update the AS3 with the correct AS3 in the correct order, but when the provider queries the state, it seems to think that all 3 BIG-IPs are running the AS3 from azf5orduksoint2.

Expected behavior:
Pass 0 of for_each deploys AS3 for azf5orduksoint1
Pass 1 of for_each deploys AS3 for azf5orduksoint2
Pass 2 of for_each deploys AS3 for azf5orduksoint3

Actual behavior:
Pass 0 of for_each
Initial: azf5orduksoint2 (incorrect)
Second Run: azf5orduksoint1 (correct)

Pass 1 of for_each
Initial: Failed (can't see what it tried to deploy, but should have been azf5orduksoint2)

Pass 2 of for_each
Initial: azf5orduksoint2 (incorrect and duplicate)
Second Run: azf5orduksoint3 (correct)**

================================================
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Refreshing state... [id=tenantList]
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Refreshing state... [id=tenantList]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Refreshing state... [id=tenantList]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # bigip_bigiq_as3.deploy_as3_to_bigips["0"] will be updated in-place
  ~ resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
      ~ as3_json         = jsonencode(
          ~ {
              ~ declaration = {
                  ~ Task1         = {
                      + azf5orduksoint1 = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool"
                              + virtualAddresses = [
                                  + "10.1.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool    = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.0.2.33",
                                          + "192.0.2.13",
                                        ]
                                      + servicePort     = 80
                                      + shareNodes      = true
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                      - azf5orduksoint2 = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool"
                              - virtualAddresses = [
                                  - "10.1.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool    = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.0.2.33",
                                          - "192.0.2.13",
                                        ]
                                      - servicePort     = 80
                                      - shareNodes      = true
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        } -> null
                        # (1 unchanged element hidden)
                    }
                  ~ target        = {
                      ~ address = "172.20.5.5" -> "172.20.5.4"
                    }
                    # (5 unchanged elements hidden)
                }
                # (3 unchanged elements hidden)
            }
        )
        id               = "tenantList"
        # (6 unchanged attributes hidden)
    }

  # bigip_bigiq_as3.deploy_as3_to_bigips["1"] is tainted, so must be replaced
-/+ resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
      ~ id               = "tenantList" -> (known after apply)
      ~ tenant_list      = "Task1" -> (known after apply)
        # (6 unchanged attributes hidden)
    }

  # bigip_bigiq_as3.deploy_as3_to_bigips["2"] will be updated in-place
  ~ resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
      ~ as3_json         = jsonencode(
          ~ {
              ~ declaration = {
                  ~ Task1         = {
                      - azf5orduksoint2 = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool"
                              - virtualAddresses = [
                                  - "10.1.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool    = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.0.2.33",
                                          - "192.0.2.13",
                                        ]
                                      - servicePort     = 80
                                      - shareNodes      = true
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        } -> null
                      + azf5orduksoint3 = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool"
                              + virtualAddresses = [
                                  + "10.1.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool    = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.0.2.33",
                                          + "192.0.2.13",
                                        ]
                                      + servicePort     = 80
                                      + shareNodes      = true
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                        # (1 unchanged element hidden)
                    }
                  ~ target        = {
                      ~ address = "172.20.5.5" -> "172.20.5.6"
                    }
                    # (5 unchanged elements hidden)
                }
                # (3 unchanged elements hidden)
            }
        )
        id               = "tenantList"
        # (6 unchanged attributes hidden)
    }

Plan: 1 to add, 2 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:

===========================================
**3rd time running Terraform apply
It still thinks that all 3 BIG-IPs are running the AS3 from azf5orduksoint2, even though BIG-IQ shows all 3 applications deployed correctly for each of the BIG-IPs. I verified in the BIG-IPs that it was deployed correctly, so it seems to be just being reported incorrectly when the state is queried... or something like that.**
===========================================
bigip_bigiq_as3.deploy_as3_to_bigips["0"]: Refreshing state... [id=tenantList]
bigip_bigiq_as3.deploy_as3_to_bigips["1"]: Refreshing state... [id=tenantList]
bigip_bigiq_as3.deploy_as3_to_bigips["2"]: Refreshing state... [id=tenantList]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # bigip_bigiq_as3.deploy_as3_to_bigips["0"] will be updated in-place
  ~ resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
      ~ as3_json         = jsonencode(
          ~ {
              ~ declaration = {
                  ~ Task1         = {
                      + azf5orduksoint1 = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool"
                              + virtualAddresses = [
                                  + "10.1.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool    = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.0.2.33",
                                          + "192.0.2.13",
                                        ]
                                      + servicePort     = 80
                                      + shareNodes      = true
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                      - azf5orduksoint2 = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool"
                              - virtualAddresses = [
                                  - "10.1.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool    = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.0.2.33",
                                          - "192.0.2.13",
                                        ]
                                      - servicePort     = 80
                                      - shareNodes      = true
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        } -> null
                        # (1 unchanged element hidden)
                    }
                  ~ target        = {
                      ~ address = "172.20.5.5" -> "172.20.5.4"
                    }
                    # (5 unchanged elements hidden)
                }
                # (3 unchanged elements hidden)
            }
        )
        id               = "tenantList"
        # (6 unchanged attributes hidden)
    }

  # bigip_bigiq_as3.deploy_as3_to_bigips["2"] will be updated in-place
  ~ resource "bigip_bigiq_as3" "deploy_as3_to_bigips" {
      ~ as3_json         = jsonencode(
          ~ {
              ~ declaration = {
                  ~ Task1         = {
                      - azf5orduksoint2 = {
                          - class       = "Application"
                          - serviceMain = {
                              - class            = "Service_HTTP"
                              - pool             = "web_pool"
                              - virtualAddresses = [
                                  - "10.1.2.10",
                                ]
                            }
                          - template    = "http"
                          - web_pool    = {
                              - class    = "Pool"
                              - members  = [
                                  - {
                                      - serverAddresses = [
                                          - "192.0.2.33",
                                          - "192.0.2.13",
                                        ]
                                      - servicePort     = 80
                                      - shareNodes      = true
                                    },
                                ]
                              - monitors = [
                                  - "http",
                                ]
                            }
                        } -> null
                      + azf5orduksoint3 = {
                          + class       = "Application"
                          + serviceMain = {
                              + class            = "Service_HTTP"
                              + pool             = "web_pool"
                              + virtualAddresses = [
                                  + "10.1.2.10",
                                ]
                            }
                          + template    = "http"
                          + web_pool    = {
                              + class    = "Pool"
                              + members  = [
                                  + {
                                      + serverAddresses = [
                                          + "192.0.2.33",
                                          + "192.0.2.13",
                                        ]
                                      + servicePort     = 80
                                      + shareNodes      = true
                                    },
                                ]
                              + monitors = [
                                  + "http",
                                ]
                            }
                        }
                        # (1 unchanged element hidden)
                    }
                  ~ target        = {
                      ~ address = "172.20.5.5" -> "172.20.5.6"
                    }
                    # (5 unchanged elements hidden)
                }
                # (3 unchanged elements hidden)
            }
        )
        id               = "tenantList"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:

**Comment by dan-da-man-86** [comment]
I uploaded the portion of the state file in ticket: C3499732

**Comment by RavinderReddyF5** [comment]
@dan-da-man-86 

how are you mapping different apps config to different bigip? are you providing separate json file with target address ? because i have used separate json with target address. i didnot hit any issues.


```
Apply complete! Resources: 2 added, 1 changed, 0 destroyed.
HYD-ML-00064448:terraform-provider-bigip chinthalapalli$
HYD-ML-00064448:terraform-provider-bigip chinthalapalli$
HYD-ML-00064448:terraform-provider-bigip chinthalapalli$
HYD-ML-00064448:terraform-provider-bigip chinthalapalli$
HYD-ML-00064448:terraform-provider-bigip chinthalapalli$ terraform show
# bigip_bigiq_as3.exampletask["0"]:
resource "bigip_bigiq_as3" "exampletask" {
    as3_json         = jsonencode(
        {
            action      = "deploy"
            class       = "AS3"
            declaration = {
                Task1         = {
                    class = "Tenant"
                }
                class         = "ADC"
                id            = "example-declaration-01"
                label         = "Task1-BIGIP-1"
                remark        = "Task 1 - HTTP Application Service"
                schemaVersion = "3.7.0"
                target        = {
                    address = "BIGIP-1"
                }
            }
            persist     = true
        }
    )
    bigiq_address    = "BIGIQ"
    bigiq_login_ref  = (sensitive value)
    bigiq_password   = (sensitive value)
    bigiq_token_auth = (sensitive value)
    bigiq_user       = (sensitive value)
    id               = "tenantList"
    tenant_list      = "Task1"
}

# bigip_bigiq_as3.exampletask["1"]:
resource "bigip_bigiq_as3" "exampletask" {
    as3_json         = jsonencode(
        {
            action      = "deploy"
            class       = "AS3"
            declaration = {
                Task2         = {
                    MyWebApp2http = {
                        class       = "Application"
                        serviceMain = {
                            class            = "Service_HTTP"
                            pool             = "web_pool"
                            virtualAddresses = [
                                "10.1.2.10",
                            ]
                        }
                        template    = "http"
                        web_pool    = {
                            class    = "Pool"
                            members  = [
                                {
                                    serverAddresses = [
                                        "192.0.2.33",
                                        "192.0.2.23",
                                    ]
                                    servicePort     = 80
                                    shareNodes      = true
                                },
                            ]
                            monitors = [
                                "http",
                            ]
                        }
                    }
                    class         = "Tenant"
                }
                class         = "ADC"
                id            = "example-declaration-01"
                label         = "Task1-BIGIP-2"
                remark        = "Task 1 - HTTP Application Service"
                schemaVersion = "3.7.0"
                target        = {
                    address = "BIGIP-2"
                }
            }
            persist     = true
        }
    )
    bigiq_address    = "BIGIQ"
    bigiq_login_ref  = (sensitive value)
    bigiq_password   = (sensitive value)
    bigiq_token_auth = (sensitive value)
    bigiq_user       = (sensitive value)
    id               = "tenantList"
    tenant_list      = "Task2"
}

# bigip_bigiq_as3.exampletask["2"]:
resource "bigip_bigiq_as3" "exampletask" {
    as3_json         = jsonencode(
        {
            action      = "deploy"
            class       = "AS3"
            declaration = {
                Task3         = {
                    MyWebApp3http = {
                        class       = "Application"
                        serviceMain = {
                            class            = "Service_HTTP"
                            pool             = "web_pool"
                            virtualAddresses = [
                                "10.1.2.12",
                            ]
                        }
                        template    = "http"
                        web_pool    = {
                            class    = "Pool"
                            members  = [
                                {
                                    serverAddresses = [
                                        "192.0.2.33",
                                        "192.0.2.23",
                                    ]
                                    servicePort     = 80
                                    shareNodes      = true
                                },
                            ]
                            monitors = [
                                "http",
                            ]
                        }
                    }
                    class         = "Tenant"
                }
                class         = "ADC"
                id            = "example-declaration-01"
                label         = "Task1-BIGIP-3"
                remark        = "Task 1 - HTTP Application Service"
                schemaVersion = "3.7.0"
                target        = {
                    address = "BIGIP-3"
                }
            }
            persist     = true
        }
    )
    bigiq_address    = "BIGIQ"
    bigiq_login_ref  = (sensitive value)
    bigiq_password   = (sensitive value)
    bigiq_token_auth = (sensitive value)
    bigiq_user       = (sensitive value)
    id               = "tenantList"
    tenant_list      = "Task3"
}

```

**Comment by RavinderReddyF5** [comment]
@dan-da-man-86 fixes added into devel branch, can you please build local binary with devel branch,and let me know if you stil see some issues.

https://github.com/F5Networks/terraform-provider-bigip/tree/devel

**Comment by trinaths** [comment]
@dan-da-man-86 Can you share your feedback after applying the above suggested changes.

**Comment by RavinderReddyF5** [comment]
@dan-da-man-86 fixed in v1.9.0, please verify
